#!/bin/bash

function upload {
    echo '[*] Uploading...'
    curl --verbose --progress-bar -u "abdullahobaied:76DE22AF894C45C2B522B715E541FCF1" -X POST https://app.testobject.com:443/api/storage/upload -H "Content-Type: application/octet-stream" --data-binary @app.apk
    echo '[*] Upload complete'
}

function runTestScript {
    echo '[*] runTestScript(): ENTER'
    bundle exec ruby basic_test_setup.rb
    echo '[*] runTestScript(): EXIT'
}

## Entry point
cd $(dirname $0) 
./makeproject
upload
runTestScript
