#!/bin/bash

# Get the current directory (/scripts/ directory)
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Traverse up to get to the root directory
SDK_DIR="$(dirname "$SCRIPTS_DIR")"
EXAMPLE_DIR=example_test

# Build adjust JAR
cd $SDK_DIR/ext/android/sdk
./build.sh

# Build adjust testing JAR
cd $SDK_DIR/ext/android/sdk/Adjust
./gradlew :adjust:clean :adjust:makeJar
cp adjust/build/outputs/adjust-*.jar $SDK_DIR

# Copy both to example project
cp $SDK_DIR/adjust-*.jar $SDK_DIR/$EXAMPLE_DIR/android/app/libs

# Build apk
cd $SDK_DIR/$EXAMPLE_DIR/android 
./gradlew assembleRelease

# copy apk to scripts dir
cp app/build/outputs/apk/app-release-unsigned.apk $SDK_DIR/$SCRIPTS_DIR/app.apk
